# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nimbupani.github.com
title: Divya Manian
subtitle: Web Development Lemonade
author: Divya Manian

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/nimbupani
subscribe_rss_webdev: http://feeds.feedburner.com/nimbu
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
permalink: /:title.html
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: categories
category_title_prefix: ""
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 30         # Posts per page on the blog index
pagination_dir: /archives  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: []
githuburl: "https://github.com/nimbupani/nimbupani.github.com/blob/source/source/_posts"
# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: 
twitter_tweet_count: 0
twitter_show_replies: false
twitter_follow_button: false
twitter_show_follower_count: false
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user: 
delicious_count: 3

# Disqus Comments
disqus_short_name: nimbublog
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-97188-1
   
# Facebook Like
facebook_like: false   
